-- [V] SEQUENCE
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    START WITH      1       -- 부터 시작(기본값 1)
    INCREMENT BY    1       -- 씩 증가(기본값 1)
    MAXVALUE        9999    -- 최대값
    MINVALUE        1       -- 최소값
    NOCYCLE     -- CYCLE : 순차번호 9999 -> 1
    NOCACHE;
SELECT * FROM DUAL;
SELECT 4*7 FROM DUAL;
SELECT FRIEND_SEQ.NEXTVAL FROM DUAL; -- 다음 순차번호 값
SELECT FRIEND_SEQ.CURRVAL FROM DUAL; -- 현재 시퀀스 값

DROP TABLE FRIEND;
CREATE TABLE FRIEND(
    NO      NUMBER(5) PRIMARY KEY,
    NAME    VARCHAR2(30) NOT NULL,
    TEL     VARCHAR2(20) UNIQUE,
    ADDRESS VARCHAR2(200),
    LAST_MODIFY DATE DEFAULT SYSDATE
);

DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    MAXVALUE 99999
    NOCYCLE NOCACHE;
    
SELECT * FROM FRIEND;
INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
    VALUES (FRIEND_SEQ.NEXTVAL, '홍길도', '010-3456-4567','서울');
INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
    VALUES (FRIEND_SEQ.NEXTVAL, '홍길도', '010-3456-4567','서울'); -- 전화번호 UNIQUE 중복 오류
INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
    VALUES (FRIEND_SEQ.NEXTVAL, '홍길동', '010-3456-4568','서울');
INSERT INTO FRIEND (NO, NAME, ADDRESS)
    VALUES (FRIEND_SEQ.NEXTVAL, '홍길동', '서울');

SELECT * FROM FRIEND;

DELETE FROM FRIEND WHERE TEL IS NULL;


-- ※ 연습문제
DROP TABLE MEMBER;
DROP TABLE MEMBER_LEVEL;
CREATE TABLE MEMBER_LEVEL(
    LEVELNO     NUMBER(5) PRIMARY KEY,
    LEVELNAME   VARCHAR2(20) NOT NULL);


CREATE TABLE MEMBER(
    mNO     NUMBER(5) PRIMARY KEY,
    mNAME   VARCHAR2(20) NOT NULL,
    mPW     VARCHAR2(8) NOT NULL,
    mMAIL   VARCHAR2(50) UNIQUE,
    mPOINT  NUMBER(10)  CHECK(mPOINT>=0),
    mRDATE  DATE DEFAULT SYSDATE,
    LEVELNO NUMBER(5) REFERENCES MEMBER_LEVEL(LEVELNO));

DROP SEQUENCE MEMBER_SEQ;
CREATE SEQUENCE MEMBER_SEQ MAXVALUE 99999 NOCACHE NOCYCLE;

INSERT INTO MEMBER_LEVEL VALUES (-1, 'BLACK');
INSERT INTO MEMBER_LEVEL VALUES (0, '일반');
INSERT INTO MEMBER_LEVEL VALUES (1, 'SILVER');
INSERT INTO MEMBER_LEVEL VALUES (2, 'GOLD');
SELECT * FROM MEMBER_LEVEL;

INSERT INTO MEMBER (mNO, mNAME, mPW, mMAIL, mPOINT, mRDATE, LEVELNO)
    VALUES (MEMBER_SEQ.NEXTVAL, '홍길동', 'AA', 'HONG@HONG.COM', 0, TO_DATE('24/09/26', 'RR/MM/DD'), 0);
INSERT INTO MEMBER (mNO, mNAME, mPW, mMAIL, mPOINT, mRDATE, LEVELNO)
    VALUES (MEMBER_SEQ.NEXTVAL, '신길동', 'BB', 'SIN@HONG.COM', 1000, TO_DATE('24/09/26', 'RR/MM/DD'), 1);
 
SELECT * FROM MEMBER;

SELECT mNO, mNAME, mRDATE, mMAIL, mPOINT, LEVELNAME 
    FROM MEMBER M, MEMBER_LEVEL L WHERE M.LEVELNO=L.LEVELNO;
